using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// A named collection of SoundDefinitions. A SoundBank is the unit of organisation AND the unit
/// of loading: load a bank to make its sounds available in the AudioRegistry, unload it to remove
/// them. Banks can be loaded globally at startup (AudioManager.startupBanks) or per-scene via a
/// SceneAudioBank component.
///
/// Banks are normally generated by "BMS AudioManager -> Generate Sound Definitions" (one per
/// category folder, plus a MasterBank of everything), but can also be hand-authored.
/// </summary>
[CreateAssetMenu(fileName = "SoundBank", menuName = "BMS AudioManager/Sound Bank")]
public class SoundBank : ScriptableObject
{
    [Tooltip("Optional friendly id used in debug logs. Falls back to the asset name when empty.")]
    public string bankId;

    [Tooltip("The SoundDefinitions contained in this bank.")]
    public List<SoundDefinition> sounds = new List<SoundDefinition>();

    /// <summary>Friendly label for logs - the bankId if set, otherwise the asset name.</summary>
    public string Label => string.IsNullOrEmpty(bankId) ? name : bankId;
}
